-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 15:18:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_projeception
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `my_projeception` ;

-- -----------------------------------------------------
-- Schema my_projeception
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_projeception` DEFAULT CHARACTER SET utf8 ;
USE `my_projeception` ;

-- -----------------------------------------------------
-- Table `my_projeception`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_projeception`.`Categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_projeception`.`Statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_projeception`.`Statut` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_projeception`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_projeception`.`Utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(55) NOT NULL,
  `prenom` VARCHAR(55) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2004) NULL,
  `est_banni` INT(1) NOT NULL,
  `Categorie_id` INT NOT NULL,
  `Statut_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Utilisateur_Categorie1_idx` (`Categorie_id` ASC),
  INDEX `fk_Utilisateur_Statut1_idx` (`Statut_id` ASC),
  CONSTRAINT `fk_Utilisateur_Categorie1`
    FOREIGN KEY (`Categorie_id`)
    REFERENCES `my_projeception`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Statut1`
    FOREIGN KEY (`Statut_id`)
    REFERENCES `my_projeception`.`Statut` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_projeception`.`Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_projeception`.`Projet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(55) NOT NULL,
  `description` VARCHAR(2004) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_projeception`.`Utilisateurs_du_projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_projeception`.`Utilisateurs_du_projet` (
  `Utilisateur_id` INT NOT NULL,
  `Projet_id` INT NOT NULL,
  INDEX `fk_Utilisateurs_du_projet_Utilisateur_idx` (`Utilisateur_id` ASC),
  INDEX `fk_Utilisateurs_du_projet_Projet1_idx` (`Projet_id` ASC),
  CONSTRAINT `fk_Utilisateurs_du_projet_Utilisateur`
    FOREIGN KEY (`Utilisateur_id`)
    REFERENCES `my_projeception`.`Utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateurs_du_projet_Projet1`
    FOREIGN KEY (`Projet_id`)
    REFERENCES `my_projeception`.`Projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
